query GetEventByAccessToken($token: String!) {
  getEventByAccessToken(accessToken: $token) {
    id
    name
    accessToken
    description
    interactions {
      id
      name
      text
      type
    }
  }
}
